export const getUsers = async (req, res) => {
  try {
    
  } 
  catch (error) {
    console.log(error);
    res.status(500).json({
      message: 'Failed To Get User ðŸ˜”',
    })
  }
}

export const getUser = async (req, res) => {
  try {
    
  } 
  catch (error) {
    console.log(error);
    res.status(500).json({
      message: 'Failed To Get User ðŸ˜”',
    })
  }
}

export const updateUser = async (req, res) => {
  try {
    
  } 
  catch (error) {
    console.log(error);
    res.status(500).json({
      message: 'Failed To Get User ðŸ˜”',
    })
  }
}

export const deleteUser = async (req, res) => {
  try {
    
  } 
  catch (error) {
    console.log(error);
    res.status(500).json({
      message: 'Failed To Get User ðŸ˜”',
    })
  }
}
